### ISSUE TITLE
Training with multiple-gpus

### ISSUE THREAD

**Issue by phongnhhn92** [kwea123/nerf_pl#26]
Hello,
I am trying to train your model using 2 GPU and I see you have an option --num_gpus in opt.py so I guess I should try this out. However, I receive this error when I use --num_gpus 2. This doesn't happen if I use 1 GPU.

```
python train.py --dataset_name blender    --root_dir /mnt/disk1/NERF/nerf_synthetic/nerf_synthetic/mic/    --N_importance 128 --img_wh 800 800 --noise_std 0    --num_epochs 16 --batch_size 4096    --optimizer radam --lr 5e-4    --lr_scheduler steplr --decay_step 2 4 8 --decay_gamma 0.5    --exp_name drum_nerf --num_gpus 2
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
CUDA_VISIBLE_DEVICES: [0,1]
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/2
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/2
----------------------------------------------------------------------------------------------------
distributed_backend=ddp
All DDP processes registered. Starting ddp with 2 processes
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/phong/paper3/Code/nerf_pl/train.py", line 180, in <module>
    trainer.fit(system)
  File "/home/phong/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 982, in fit
    self.ddp_train(process_idx=task, q=None, model=model)
  File "/home/phong/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_lightning/trainer/distrib_data_parallel.py", line 560, in ddp_train
    results = self.run_pretrain_routine(model)
  File "/home/phong/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1185, in run_pretrain_routine
    self.reset_val_dataloader(ref_model)
  File "/home/phong/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_lightning/trainer/data_loading.py", line 343, in reset_val_dataloader
    self.num_val_batches, self.val_dataloaders = self._reset_eval_dataloader(model, 'val')
  File "/home/phong/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_lightning/trainer/data_loading.py", line 270, in _reset_eval_dataloader
    dataloaders = self.request_dataloader(getattr(model, f'{mode}_dataloader'))
  File "/home/phong/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_lightning/trainer/data_loading.py", line 364, in request_dataloader
    dataloader = dataloader_fx()
  File "/home/phong/paper3/Code/nerf_pl/train.py", line 97, in val_dataloader
    return DataLoader(self.val_dataset,
  File "/home/phong/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 594, in __getattr__
    type(self).__name__, name))
AttributeError: 'NeRFSystem' object has no attribute 'val_dataset'
```

**Comment by kwea123** [comment]
Which version of pytorch lightning are you using? From the console it looks like it's 0.8.x.
My code is written for 0.7.5 as in `requirements.txt`, so either you revert the version, or you can change 
https://github.com/kwea123/nerf_pl/blob/a535ee8271d2bff35602a19d1eed09fcf836bec7/train.py#L73
to
`def setup(self, stage):` (only the function name)
and it should work in version 0.8.x (I work with 0.8.4)

**Comment by phongnhhn92** [comment]
Hi, It works ! I am kind a new to this pytorch lightning but just in case I want to train my model using a single GPU then which function name should I use ? setup() or prepare_data(). Will the setup() function works in case of single GPU training ?

**Comment by kwea123** [comment]
Yes, it works for any number of gpus
